config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/timeline'
  devise_for :users
  resources :users, only: [:index, :show]
  patch 'users/:id/follow', to: 'users#follow', as: :user_follow
  patch 'users/:id/unfollow', to: 'users#unfollow', as: :user_unfollow

  resources :followers, only: [:index]
  resources :followings, only: [:index]

  patch 'tweet/:id/retweet', to: 'tweets#retweet', as: :tweet_retweet

  root 'tweets#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/following.rb
class Following < ApplicationRecord
  searchkick
  belongs_to :user
  belongs_to :follower, class_name: 'User'
end

app/models/reply.rb
class Reply < ApplicationRecord
  belongs_to :tweet
  belongs_to :tweet_reply, class_name: 'Tweet'

  validates_presence_of :tweet_id, :tweet_reply_id
end

app/models/retweet.rb
class Retweet < ApplicationRecord
  belongs_to :tweet
  belongs_to :user

  validates_presence_of :user_id, :tweet_id

  def to_s
    "Retweet from @#{self.tweet.user.username}:\n #{self.tweet.message}"
  end

  def timestamp
    created_at.strftime('%H:%M:%S %d %B %Y')
  end
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  has_many :replies
  has_many :tweets_reply, through: :replies
  has_many :retweets
  belongs_to :user

  validates :message, presence: true, length: {minimum: 2, maximum: 144}
  validates_presence_of :user_id
  
  def timestamp
    created_at.strftime('%H:%M:%S %d %B %Y')
  end
end

app/models/user.rb
class User < ApplicationRecord
  searchkick

  has_many :tweets
  has_many :retweets
  has_many :followings
  has_many :followers, through: :followings
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates_presence_of :name, :username

  def follow?(user)
    user.followers.include? self
  end

  def followings_and_me
    users_tweets = Following.where(follower_id: self.id).pluck(:user_id)
    users_tweets << self.id
  end

  def timeline
    @tweets = Tweet.where(user_id: self.followings_and_me).order('created_at desc')
    @retweets = Retweet.where(user_id: self.followings_and_me).order('created_at desc')
    @tweets = @tweets + @retweets
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_in, keys: [:username])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :name])
  end
end

app/controllers/followers_controller.rb
class FollowersController < ApplicationController
  before_action :authenticate_user!

  # GET /users
  # GET /users.json
  def index
    if params[:q].nil?
      @followers = current_user.followers.where.not(id: current_user.id).limit(50)
    else
      @followers = current_user.followers.search params[:q]
    end
  end

end

app/controllers/followings_controller.rb
class FollowingsController < ApplicationController
  before_action :authenticate_user!

  # GET /users
  # GET /users.json
  def index
    if params[:q].nil?
      @followings = Following.where(follower_id: current_user.id).limit(50)
    else
      @followings = Following.search params[:q], where: { follower_id: current_user.id }
    end
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_tweet, only: :retweet

  def index
    @tweets = current_user.timeline.sort_by(&:created_at).reverse
    @tweet = Tweet.new
  end

  def retweet
    @retweet = Retweet.new user_id: current_user.id, tweet_id: @tweet.id
    if @retweet.save
      redirect_to :root
    end
  end

  private
  def set_tweet
    @tweet = Tweet.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :follow, :unfollow]

  # GET /users
  # GET /users.json
  def index
    if params[:q].nil?
      @users = User.where.not(id: current_user.id).limit(50)
    else
      @users = User.search params[:q]
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @followers = @user.followers.joins(:users)
  end

  def follow
    @following = Following.new(user: @user , follower: current_user)
    if @following.save
      render :show
    end
  end

  def unfollow
    @following = Following.where(user_id: @user.id , follower_id: current_user.id).first
    if @following.destroy
      render :show
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/followers/index.html.slim
.panel.panel-default
  .panel-heading Followers
  .panel-body
    = form_for followers_path, method: :get do |f|
      #custom-search-input
        .input-group.col-md-12
          input.form-control.input-lg placeholder="Buscar" name="q" id="q" type="text" /
          span.input-group-btn
            button.btn.btn-info.btn-lg type="button" 
              i.glyphicon.glyphicon-search
  /! List group
  .list-group#users
    - @followers.each do |follower|
      = link_to  follower, class: 'list-group-item'
        h5.list-group-item-heading = "@#{follower.username}"
        p.list-group-item-text = follower.email

app/views/followings/index.html.slim
.panel.panel-default
  .panel-heading Followings
  .panel-body
    = form_for followings_path, method: :get do |f|
      #custom-search-input
        .input-group.col-md-12
          input.form-control.input-lg placeholder="Buscar" name="q" id="q" type="text" /
          span.input-group-btn
            button.btn.btn-info.btn-lg type="button" 
              i.glyphicon.glyphicon-search
  /! List group
  .list-group#users
    - @followings.each do |following|
      = link_to  following.follower, class: 'list-group-item'
        h5.list-group-item-heading = "@#{following.follower.username}"
        p.list-group-item-text = following.follower.email

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>Twitter CL</title>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>
    <body>
        <div id="wrapper">
            <!-- Sidebar -->
            <div id="sidebar-wrapper">
                <ul class="sidebar-nav">
                    <li class="sidebar-brand">
                        <a href="#">
                            Twitter CL
                        </a>
                    </li>
                    <% if current_user %>
                      <li>
                        <a href="">
                          @<%= current_user.username %>
                        </a>
                      </li>
                    <% end %>
                    <li>
                      <%= link_to "Home", root_path %>
                    </li>
                    <li>
                      <%= link_to "Search users", users_path %>
                    </li>
                    <li>
                      <%= link_to "Followers", followers_path %>
                    </li>
                    <li>
                      <%= link_to "Following", followings_path %>
                    </li>
                    <li>
                        <%= link_to "Account", edit_user_registration_path %>
                    </li>
                    <li>
                      <%= link_to "Logout", destroy_user_session_path, method: :delete %>
                    </li>
                </ul>
            </div>
            <!-- /#sidebar-wrapper -->

            <!-- Page Content -->
            <div id="page-content-wrapper">
                <div class="container-fluid">
                    <%= yield %>
                </div>
            </div>
            <!-- /#page-content-wrapper -->

        </div>
        <!-- /#wrapper -->
    </body>
</html>

app/views/tweets/_tweet.html.slim
a.list-group-item href="#" 
  h5.list-group-item-heading = "@#{tweet.user.username} às #{tweet.timestamp}"
  p.list-group-item-text = tweet.try(:message) || tweet.try(:to_s)
  - if tweet.try(:message)
    = link_to tweet_retweet_path(tweet), method: :patch, class: 'btn btn-info', title: 'Reply'  do
      i.glyphicon.glyphicon-share-alt

app/views/tweets/index.html.slim
.panel.panel-default
  .panel-heading Timeline
  .panel-body
    = form_for @tweet, url: '#' do |f|
      #custom-search-input
        .input-group.col-md-12
          input.form-control.input-lg placeholder="Enviar" name="tweet[message]" id="tweet_message" type="text_area" /
          span.input-group-btn
            button.btn.btn-info.btn-lg type="submit" 
              i.glyphicon.glyphicon-send
  /! List group
  .list-group#messages
    = render partial: 'tweet', collection: @tweets

app/views/users/index.html.slim
.row
  = form_for users_path, method: :get do |f|
    #custom-search-input
      .input-group.col-md-12
        input.form-control.input-lg placeholder="Buscar" name="q" id="q" type="text" /
        span.input-group-btn
          button.btn.btn-info.btn-lg type="button" 
            i.glyphicon.glyphicon-search
      
table
  thead
    tr
      th
      th
      th

  tbody
    - @users.each do |user|
      tr
        td 
          span.text-muted
            = "@#{user.username}"
            |  email: 
            = user.email
        td = link_to 'Show', user

app/views/users/show.html.slim
p#notice = notice
.panel.panel-default
  .panel-heading Usuário @#{@user.username}
  .panel-body
    .row
      .col-md-12
        p.card-text
          span.text-muted
            | Email: 
            = @user.email
            br
            | Nome: 
            = @user.name
  .list-group#users
    - @user.followers.each do |follower|
      = link_to follower, class: 'list-group-item'
        h5.list-group-item-heading = "@#{follower.username}"
        p.list-group-item-text = follower.email
  .list-group#users
    .btn-group role="group" 
      = link_to 'Back', users_path, class: 'btn btn-primary'
      - if current_user.follow?(@user)
        = link_to 'Unfollow', user_unfollow_path, method: :patch, class:'btn btn-primary'
      - else 
        = link_to 'Follow', user_follow_path, method: :patch, class:'btn btn-primary'